FROM rocm-vistral7b-base
WORKDIR /app

COPY /main.py /app/main.py

EXPOSE 8080

CMD [ "python3", "main.py","8080","cuda"]

#sudo apt update && sudo apt install -y git python3-pip python3-venv python3-dev libstdc++-12-dev 
#docker build -f dockerfile -t rocm-vistral7b .
#docker rm --force rocm_vistral7b_8880
#with volume# docker run --privileged -d --restart always -p 11111:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G --name rocm_vistral7b_8880 -v /work/Ner_Llm_Gpt/mistralvn:/app rocm-vistral7b  

#no volue# docker run --privileged -d --restart always -p 11111:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G --name rocm_vistral7b_8880 rocm-vistral7b  
#docker run --privileged -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G rocm/pytorch:latest
#docker run -it --privileged --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 24G 