# FROM rocm-vistral7b-base
FROM  nvidia/cuda:12.4.1-devel-ubuntu22.04 
USER root
WORKDIR /app

# ENV HCC_AMDGPU_TARGET "gfx1103"
# ENV HSA_OVERRIDE_GFX_VERSION "11.0.0"
# ENV HIP_VISIBLE_DEVICES "0"
# cp -r /home/emas_ops/llm/Vistral-7B-Chat /home/emas_ops/llm/Ner_Llm_Gpt/mistralvn/Vistral-7B-Chat
COPY /main.py /app/main.py
# COPY /testrocm.py /app/testrocm.py
COPY /Vistral-7B-Chat /app/Vistral-7B-Chat

EXPOSE 8880

CMD [ "python3", "main.py","8880","cuda"]


# sudo docker build -f dockerfile -t llama-vistral7b-gpu .

# sudo docker run --user root --privileged -d --restart always --gpus all -p 8880:8880 --name llama-vistral7b-gpu_8880 llama-vistral7b-gpu

# sudo docker rm -f llama-vistral7b-gpu_8880
# sudo docker rmi -f llama-vistral7b-gpu
# sudo docker inspect --format='{{.State.Status}}' llama-vistral7b-gpu_8880

# sudo docker logs -f --tail 10 llama-vistral7b-gpu_8880


#sudo apt update && sudo apt install -y git python3-pip python3-venv python3-dev libstdc++-12-dev 
#docker build -f dockerfile -t rocm-vistral7b .
#docker rm --force rocm_vistral7b_8880
#with volume# docker run --user root --privileged -d --restart always -p 11111:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G --name rocm_vistral7b_8880 -v /work/Ner_Llm_Gpt/mistralvn:/app rocm-vistral7b  

#no volue# docker run --user root --privileged -d --restart always -p 11111:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G --name rocm_vistral7b_8880 rocm-vistral7b  
#docker run --user root --privileged -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G rocm/pytorch:latest
#docker run --user root -it --privileged --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 24G 