FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 
USER root
WORKDIR /app 
EXPOSE 8880
COPY /bin.gpu/ /app/bin/

COPY /favicon.ico /app/favicon.ico
COPY /favicon.png /app/favicon.png

COPY /Vistral-7B-Chat.gpu.gguf /app/Vistral-7B-Chat.gguf
ENV LLAMA_CUDA=1
ENV LLAMA_CURL=1
ENV CUDA_DOCKER_ARCH=all
ENV LC_ALL=C.utf8
CMD [ "/bin/sh", "-c", "./bin/server -m '/app/Vistral-7B-Chat.gguf' -c 2048 --host 0.0.0.0 --port 8880"]

# "/work/llm/Ner_Llm_Gpt/mistralvn/bin.gpu/server" -m '/work/llm/Ner_Llm_Gpt/mistralvn/Vistral-7B-Chat.gpu.gguf' -c 2048 --host 0.0.0.0 --port 8880

# sudo docker build -f dockerfile.gpu.llamaccp -t llama-vistral7b-gpu .

# sudo docker run --user root --privileged -d --restart always --gpus all -p 11111:8880 --name llama-vistral7b-gpu_8880 llama-vistral7b-gpu


#./server -m "/work/llm/llama.cpp/Vistral-7B-Chat.gguf" -c 2048

#sudo apt update && sudo apt install -y git python3-pip python3-venv python3-dev libstdc++-12-dev 

# sudo docker rmi -f b6548eacb063
# sudo lsof -i -P -n | grep LISTEN
# docker rm -v 123f7027e418a18595526a066afe7d9d0c9cfa1e705f579583ec8f5a00975e69

#docker rm --force rocm_vistral7b_8880
#with volume# docker run --user root --privileged -d --restart always -p 8880:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G --name rocm_vistral7b_8880 -v /work/Ner_Llm_Gpt/mistralvn:/app rocm-vistral7b  

#no volue# docker run --user root --privileged -d --restart always -p 11111:8080 -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G --name rocm_vistral7b_8880 rocm-vistral7b  
#docker run --user root --privileged -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 8G rocm/pytorch:latest
#docker run --user root -it --privileged --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --group-add render --ipc=host --shm-size 24G 